main: de.MrX13415.ButtonLock.ButtonLock

name: ButtonLock
version: 0.5 (MC 1.7.3)
description: Lock Buttons, Levers and Blocks
author: MrX13415

commands:
  setPassword:
    aliases: setpw
    description: Set, changes or removes a password
    usage: |
           <command> <password>   Set/changes a password
           <command>              Removes a password 
  Password:
    aliases: pw
    description: Enter a password
    usage: |
           <command> <password>   Enter a password