main: de.MrX13415.ButtonLock.ButtonLock

name: ButtonLock
version: 0.8 (MC 1.7.3)
description: Lock Buttons, Levers and Blocks
author: MrX13415

commands:
  setpassword:
    aliases: setpw
    description: Set, changes or removes a password
    usage: |
           <command> <password>   Set/changes a password
           <command>              Removes a password 
  password:
    aliases: pw
    description: Enter a password
    usage: |
           <command> <password>   Enter a password
  singleusepassword:
    aliases: supw
    description: Add or remove a single-use-password
    usage: |
           <command> <add|remove> <password>  add/removes a single-use-password
  buttonlock:
    aliases: bl
    description: Managed Buttonlock and locked groups
    usage: |
           <command> <save|reload|reset>  reload/save/reset all config-files from Buttonlock
           <command> group forcePassword <true|false>  enforces a password every time or not ... 
           <command> group costs <costs>  change the costs of a locked group ... 
           <command> group <add|remove>  adds or removes a Block to or from a locked group ... 